# Generated by Django 5.1.4 on 2025-01-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_id',
            field=models.IntegerField(default=0),
        ),
    ]
