# Generated by Django 5.1.4 on 2025-01-28 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_order_table_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table_id',
        ),
    ]
